alias dng='WINEPREFIX="$HOME/wine-dng" wine "$HOME/wine-dng/drive_c/Program Files/Adobe/Adobe DNG Converter/Adobe DNG Converter.exe"'
alias tensorflow="source ~/envs/tensorflow/bin/activate"
alias emc="/usr/local/emercoin/bin/emercoin-cli"
alias style="ant style"
alias tests="vendor/bin/phpunit --configuration=build/phpunit.xml --no-coverage"
alias cls="clear"
alias oblique="fortune /usr/share/games/fortunes/oblique/"
alias nvidia="sudo prime-select nvidia"
alias intel="sudo prime-select intel"
alias updates="sudo apt update && sudo apt list --upgradeable"
alias upgrade="sudo apt update && sudo apt dist-upgrade -y"
alias vim="nvim"
alias mutt="neomutt"
alias swagger-codegen="java -jar ~/Applications/SwaggerGen/swagger-codegen-cli.jar"
alias openapi-gen="java -jar ~/Applications/open-api/openapi-generator-cli.jar"
alias daily="vim  ~/Documents/ChinaNetCloud/Reports/DailyReport.md"
alias emacs="emacs -nw"
alias doas="doas -- "
alias sudo="doas" 
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
